#[derive(Debug, Hash, Eq, PartialEq)]
pub enum KeyCode {
    Backspace,
    Tab,
    Enter,
    Shift,
    Ctrl,
    Alt,
    Escape,
    Space,
    Pgup,
    Pgdown,
    End,
    Home,
    Left,
    Up,
    Right,
    Down,
    Insert,
    Delete,
    QwertyEquals,
    QwertyMinus,
    QwertyTilde,
    QwertyBracketLeft,
    QwertyBracketRight,
    QwertySemicolon,
    QwertyQuote,
    QwertyBackslash,
    QwertyComma,
    QwertyPeriod,
    QwertySlash,
    IntlBackslash,
    LeftWindowKey,
    RightWindowKey,
    ContextMenu,
    PrintScreen,
    PauseBreak,
    CapsLock,
    NumLock,
    ScrollLock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    NumpadMult,
    NumpadAdd,
    NumpadEnter,
    NumpadSub,
    NumpadDot,
    NumpadDiv,
    MouseLeft,
    MouseRight,
    MouseMiddle,
    MouseBack,
    MouseForward,
    MouseWheelUp,
    MouseWheelDown,
    LocLeft,
    LocRight,
    Unknown,
}

#[cfg(target_arch = "wasm32")]
impl From<crate::window::event::key::KeyCode> for KeyCode {
    fn from(key_code: crate::window::event::key::KeyCode) -> KeyCode {
        match key_code {
            crate::window::event::key::BACKSPACE => KeyCode::Backspace,
            crate::window::event::key::TAB => KeyCode::Tab,
            crate::window::event::key::ENTER => KeyCode::Enter,
            crate::window::event::key::SHIFT => KeyCode::Shift,
            crate::window::event::key::CTRL => KeyCode::Ctrl,
            crate::window::event::key::ALT => KeyCode::Alt,
            crate::window::event::key::ESCAPE => KeyCode::Escape,
            crate::window::event::key::SPACE => KeyCode::Space,
            crate::window::event::key::PGUP => KeyCode::Pgup,
            crate::window::event::key::PGDOWN => KeyCode::Pgdown,
            crate::window::event::key::END => KeyCode::End,
            crate::window::event::key::HOME => KeyCode::Home,
            crate::window::event::key::LEFT => KeyCode::Left,
            crate::window::event::key::UP => KeyCode::Up,
            crate::window::event::key::RIGHT => KeyCode::Right,
            crate::window::event::key::DOWN => KeyCode::Down,
            crate::window::event::key::INSERT => KeyCode::Insert,
            crate::window::event::key::DELETE => KeyCode::Delete,
            crate::window::event::key::QWERTY_EQUALS => KeyCode::QwertyEquals,
            crate::window::event::key::QWERTY_MINUS => KeyCode::QwertyMinus,
            crate::window::event::key::QWERTY_TILDE => KeyCode::QwertyTilde,
            crate::window::event::key::QWERTY_BRACKET_LEFT => KeyCode::QwertyBracketLeft,
            crate::window::event::key::QWERTY_BRACKET_RIGHT => KeyCode::QwertyBracketRight,
            crate::window::event::key::QWERTY_SEMICOLON => KeyCode::QwertySemicolon,
            crate::window::event::key::QWERTY_QUOTE => KeyCode::QwertyQuote,
            crate::window::event::key::QWERTY_BACKSLASH => KeyCode::QwertyBackslash,
            crate::window::event::key::QWERTY_COMMA => KeyCode::QwertyComma,
            crate::window::event::key::QWERTY_PERIOD => KeyCode::QwertyPeriod,
            crate::window::event::key::QWERTY_SLASH => KeyCode::QwertySlash,
            crate::window::event::key::INTL_BACKSLASH => KeyCode::IntlBackslash,
            crate::window::event::key::LEFT_WINDOW_KEY => KeyCode::LeftWindowKey,
            crate::window::event::key::RIGHT_WINDOW_KEY => KeyCode::RightWindowKey,
            crate::window::event::key::CONTEXT_MENU => KeyCode::ContextMenu,
            crate::window::event::key::PAUSE_BREAK => KeyCode::PauseBreak,
            crate::window::event::key::CAPS_LOCK => KeyCode::CapsLock,
            crate::window::event::key::NUM_LOCK => KeyCode::NumLock,
            crate::window::event::key::SCROLL_LOCK => KeyCode::ScrollLock,
            crate::window::event::key::NUMPAD_0 => KeyCode::Numpad0,
            crate::window::event::key::NUMPAD_1 => KeyCode::Numpad1,
            crate::window::event::key::NUMPAD_2 => KeyCode::Numpad2,
            crate::window::event::key::NUMPAD_3 => KeyCode::Numpad3,
            crate::window::event::key::NUMPAD_4 => KeyCode::Numpad4,
            crate::window::event::key::NUMPAD_5 => KeyCode::Numpad5,
            crate::window::event::key::NUMPAD_6 => KeyCode::Numpad6,
            crate::window::event::key::NUMPAD_7 => KeyCode::Numpad7,
            crate::window::event::key::NUMPAD_8 => KeyCode::Numpad8,
            crate::window::event::key::NUMPAD_9 => KeyCode::Numpad9,
            crate::window::event::key::A => KeyCode::A,
            crate::window::event::key::B => KeyCode::B,
            crate::window::event::key::C => KeyCode::C,
            crate::window::event::key::D => KeyCode::D,
            crate::window::event::key::E => KeyCode::E,
            crate::window::event::key::F => KeyCode::F,
            crate::window::event::key::G => KeyCode::G,
            crate::window::event::key::H => KeyCode::H,
            crate::window::event::key::I => KeyCode::I,
            crate::window::event::key::J => KeyCode::J,
            crate::window::event::key::K => KeyCode::K,
            crate::window::event::key::L => KeyCode::L,
            crate::window::event::key::M => KeyCode::M,
            crate::window::event::key::N => KeyCode::N,
            crate::window::event::key::O => KeyCode::O,
            crate::window::event::key::P => KeyCode::P,
            crate::window::event::key::Q => KeyCode::Q,
            crate::window::event::key::R => KeyCode::R,
            crate::window::event::key::S => KeyCode::S,
            crate::window::event::key::T => KeyCode::T,
            crate::window::event::key::U => KeyCode::U,
            crate::window::event::key::V => KeyCode::V,
            crate::window::event::key::W => KeyCode::W,
            crate::window::event::key::X => KeyCode::X,
            crate::window::event::key::Y => KeyCode::Y,
            crate::window::event::key::Z => KeyCode::Z,
            crate::window::event::key::F1 => KeyCode::F1,
            crate::window::event::key::F2 => KeyCode::F2,
            crate::window::event::key::F3 => KeyCode::F3,
            crate::window::event::key::F4 => KeyCode::F4,
            crate::window::event::key::F5 => KeyCode::F5,
            crate::window::event::key::F6 => KeyCode::F6,
            crate::window::event::key::F7 => KeyCode::F7,
            crate::window::event::key::F8 => KeyCode::F8,
            crate::window::event::key::F9 => KeyCode::F9,
            crate::window::event::key::F10 => KeyCode::F10,
            crate::window::event::key::F11 => KeyCode::F11,
            crate::window::event::key::F12 => KeyCode::F12,
            crate::window::event::key::F13 => KeyCode::F13,
            crate::window::event::key::F14 => KeyCode::F14,
            crate::window::event::key::F15 => KeyCode::F15,
            crate::window::event::key::F16 => KeyCode::F16,
            crate::window::event::key::F17 => KeyCode::F17,
            crate::window::event::key::F18 => KeyCode::F18,
            crate::window::event::key::F19 => KeyCode::F19,
            crate::window::event::key::F20 => KeyCode::F20,
            crate::window::event::key::F21 => KeyCode::F21,
            crate::window::event::key::F22 => KeyCode::F22,
            crate::window::event::key::F23 => KeyCode::F23,
            crate::window::event::key::F24 => KeyCode::F24,
            crate::window::event::key::NUMPAD_MULT => KeyCode::NumpadMult,
            crate::window::event::key::NUMPAD_ADD => KeyCode::NumpadAdd,
            crate::window::event::key::NUMPAD_ENTER => KeyCode::NumpadEnter,
            crate::window::event::key::NUMPAD_SUB => KeyCode::NumpadSub,
            crate::window::event::key::NUMPAD_DOT => KeyCode::NumpadDot,
            crate::window::event::key::NUMPAD_DIV => KeyCode::NumpadDiv,
            crate::window::event::key::MOUSE_LEFT => KeyCode::MouseLeft,
            crate::window::event::key::MOUSE_RIGHT => KeyCode::MouseRight,
            crate::window::event::key::MOUSE_MIDDLE => KeyCode::MouseMiddle,
            crate::window::event::key::MOUSE_BACK => KeyCode::MouseBack,
            crate::window::event::key::MOUSE_FORWARD => KeyCode::MouseForward,
            crate::window::event::key::MOUSE_WHEEL_UP => KeyCode::MouseWheelUp,
            crate::window::event::key::MOUSE_WHEEL_DOWN => KeyCode::MouseWheelDown,
            crate::window::event::key::LOC_LEFT => KeyCode::LocLeft,
            crate::window::event::key::LOC_RIGHT => KeyCode::LocRight,
            _ => KeyCode::Unknown,
        }
    }
}
